FROM node:14 AS builder
WORKDIR /usr/src/frontend
COPY frontend/ ./
RUN npm install
RUN npm run build


FROM nginx:1.16.0-alpine
COPY --from=builder /usr/src/frontend/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]