FROM node:14
WORKDIR /usr/src/app
COPY backend/ ./
RUN npm install
RUN npm install pm2 -g
RUN npm uninstall bcrypt
RUN npm i bcrypt
RUN npm run build
EXPOSE 4000
RUN pm2 start ./dist/server.js
CMD ["pm2-runtime","./dist/server.js"]